name: Build Docker Image.

# Trigger workflow on push to master branch
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build & Push Docker Image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: helloworldblog.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t helloworldblog.azurecr.io/microservice:latest .
      - name: Push Docker Image to ACR
        run: docker push helloworldblog.azurecr.io/microservice:latest
