name: Build Docker Image.

# Trigger workflow on push to master branch
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build & Push Docker Image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: gameregistry001.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t gameregistry001.azurecr.io/microservice:latest .
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az login --service-principal -u 246cfd43-77c5-4c63-8f77-d6a19a3876ec -p QMI8Q~tCFMcT85QTc1Kdn7hanAEj7nBCnpq3Vc7b --tenant e4e34038-ea1f-4882-b6e8-ccd776459ca0
            az account set --subscription 737d1672-96a9-4ba4-b12c-8027ef27ab4e
      - name: Push Docker Image to ACR
        run: docker push gameregistry001.azurecr.io/microservice:latest
